include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: ^3.1.3

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - .dart_tool/**
    - lib/generated_plugin_registrant.dart
    - test/**.mocks.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**.config.dart"

linter:
  rules:
    avoid_print: false
    no_leading_underscores_for_local_identifiers: false
    unawaited_futures: true
